Project Status Report
1. Project Overview
This repository is a small data pipeline and dashboard for analyzing Tamil Nadu assembly–related YouTube comments. It has two main components:

election.py — data collection, cleaning, sentiment analysis, entity detection, and CSV export
app.py — Streamlit dashboard for visualizing the derived data
The workflow is:

Fetch videos and comments from YouTube
Clean and filter comments
Detect sentiment and political entities
Save analysis outputs as CSV
Load CSV data in Streamlit and display charts
2. Files and Roles
Core Python files
election.py

Uses googleapiclient to query the YouTube Data API
Searches for Tamil Nadu Assembly
Collects up to 100 videos, then processes a subset of videos meeting filters
Fetches up to 500 comments per video
Cleans comments:
removes URLs
removes emojis
removes non-word characters except Tamil and English
converts to lowercase
Filters invalid noise comments
Detects party/entity mentions via keyword matching
Uses transformers sentiment pipeline with cardiffnlp/twitter-xlm-roberta-base-sentiment
Saves:
videos_master.csv
comments_cleaned.csv
sentiment_summary.csv
app.py

Uses Streamlit for a dashboard
Loads:
comments_cleaned.csv
sentiment_summary.csv
Displays:
sample comments
sentiment distribution by party
overall sentiment pie chart
party mentions bar chart
leader mentions bar chart
top discussion keywords via CountVectorizer
Data files
comments_cleaned.csv
Generated by election.py
Contains cleaned comments, original comment text, sentiment, and detected entities
sentiment_summary.csv
Generated by election.py
Contains aggregated sentiment counts per entity/party
videos_master.csv
Generated by election.py
Contains metadata for fetched YouTube videos
Environment and config
tn_election_env
Python virtual environment directory
.env
Expected to include YOUTUBE_API_KEY
Not shown in content, but required by election.py
.gitignore
excludes .env, virtual envs, cache, logs, and data files
Dependencies
requirements.txt is present but appears encoded as UTF-16 in the repo snapshot
Visible dependency lines include:
annotated-types==0.7.0
anyio==4.13.0
certifi==2026.2.25
cffi==2.0.0
charset-normalizer==3.4.7
3. Current Implementation Details
election.py logic
load_dotenv()
Reads YOUTUBE_API_KEY from env
Config:
QUERY = "Tamil Nadu Assembly"
MAX_VIDEOS = 100
COMMENTS_PER_VIDEO = 500
Sentiment model:
cardiffnlp/twitter-xlm-roberta-base-sentiment
Returns Positive, Negative, or Neutral
Truncates text to 512 tokens
Video fetch:
youtube.search().list(...)
collects up to MAX_VIDEOS
Comment fetch:
youtube.commentThreads().list(...)
stops on disabled comments
Cleaning:
removes URLs, emojis, non-Tamil/English chars
lowercases and trims
Entity detection:
parties detected by keywords
DMK, AIADMK, BJP, TVK
Output:
creates comments_cleaned.csv
creates sentiment summary aggregated by entity
app.py visualizations
Sample comments table
Bar chart of sentiment summary by party
Overall sentiment pie chart
Party mentions count using entities CSV field
Leader mentions from a keyword map:
Stalin, EPS, Annamalai, Vijay
Top topics using CountVectorizer on cleaned text
4. What Has Been Done So Far
Data collection pipeline is implemented and runs through full extraction and export
Sentiment analysis is integrated using a multilingual transformer
Entity recognition is implemented via keyword matching
Streamlit dashboard is implemented to consume the exported CSVs
Output artifacts exist in the repo:
comments_cleaned.csv
sentiment_summary.csv
videos_master.csv
5. Important Notes for a New Developer
Setup
Activate or create a Python environment
Install dependencies from requirements.txt
Add YOUTUBE_API_KEY to .env
Run python election.py to generate CSV files
Run streamlit run app.py to launch the dashboard
Missing / Next Improvements
requirements.txt should be re-saved in UTF-8 for reliability
Add a README.md documenting setup and usage
Add error handling for missing CSV files in app.py
Improve entities detection to handle word boundaries and Tamil variations
Consider merging data generation into app or adding a separate CLI/command